// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD... (tu API key web)',
    appId: '1:...:web:...',
    messagingSenderId: '...',
    projectId: 'planea-proyecto',
    authDomain: 'planea-proyecto.firebaseapp.com',
    storageBucket: 'planea-proyecto.appspot.com',
    measurementId: 'G-...',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD... (tu API key android)',
    appId: '1:...:android:...',
    messagingSenderId: '...',
    projectId: 'planea-proyecto',
    storageBucket: 'planea-proyecto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD... (tu API key iOS)',
    appId: '1:...:ios:...',
    messagingSenderId: '...',
    projectId: 'planea-proyecto',
    storageBucket: 'planea-proyecto.appspot.com',
    iosBundleId: 'com.example.proyeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD... (tu API key macOS)',
    appId: '1:...:macos:...',
    messagingSenderId: '...',
    projectId: 'planea-proyecto',
    storageBucket: 'planea-proyecto.appspot.com',
    iosBundleId: 'com.example.proyeto',
  );
}
